# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desinge.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(70, 50, 631, 471))
        self.widget.setObjectName("widget")
        self.windows = QtWidgets.QLabel(self.widget)
        self.windows.setGeometry(QtCore.QRect(0, 0, 631, 471))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setStrikeOut(False)
        self.windows.setFont(font)
        self.windows.setToolTipDuration(1)
        self.windows.setStyleSheet("background-color: rgb(49, 115, 237);\n"
"border-radius: 20px;")
        self.windows.setText("")
        self.windows.setWordWrap(True)
        self.windows.setObjectName("windows")
        self.sub_windows = QtWidgets.QLabel(self.widget)
        self.sub_windows.setGeometry(QtCore.QRect(320, 0, 311, 471))
        self.sub_windows.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"border-top-right-radius : 18px;\n"
"border-bottom-right-radius : 18px")
        self.sub_windows.setText("")
        self.sub_windows.setObjectName("sub_windows")
        self.label_text_3 = QtWidgets.QPlainTextEdit(self.widget)
        self.label_text_3.setEnabled(False)
        self.label_text_3.setGeometry(QtCore.QRect(10, 100, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_text_3.setFont(font)
        self.label_text_3.setAccessibleDescription("")
        self.label_text_3.setStyleSheet("\n"
"background-color: rgb(49, 115, 237);\n"
"color: rgb(255, 255, 255);")
        self.label_text_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_text_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_text_3.setLineWidth(0)
        self.label_text_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_text_3.setBackgroundVisible(False)
        self.label_text_3.setObjectName("label_text_3")
        self.output = QtWidgets.QLabel(self.widget)
        self.output.setGeometry(QtCore.QRect(30, 170, 271, 221))
        self.output.setStyleSheet("image: url(:/newPrefix/Frame 1.svg);")
        self.output.setText("")
        self.output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.output.setObjectName("output")
        self.input_text = QtWidgets.QTextEdit(self.widget)
        self.input_text.setGeometry(QtCore.QRect(340, 170, 271, 141))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_text.setFont(font)
        self.input_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_text.setAutoFillBackground(True)
        self.input_text.setStyleSheet("image: url(:/newPrefix/Rectangle 3.svg);\n"
"color: rgb(255, 255, 255);\n"
"border-image: url(:/newPrefix/Rectangle 3.svg);")
        self.input_text.setFrameShape(QtWidgets.QFrame.VLine)
        self.input_text.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_text.setLineWidth(27)
        self.input_text.setMidLineWidth(16)
        self.input_text.setTabChangesFocus(True)
        self.input_text.setObjectName("input_text")
        self.Button_analysis = QtWidgets.QPushButton(self.widget)
        self.Button_analysis.setGeometry(QtCore.QRect(410, 340, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.Button_analysis.setFont(font)
        self.Button_analysis.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_analysis.setToolTip("")
        self.Button_analysis.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"border: 0px;\n"
"selection-background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 255, 255);\n"
"gridline-color: rgb(255, 255, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"image: url(:/newPrefix/Rectangle 4.svg);\n"
"image: url(:/newPrefix/Rectangle 4.svg);\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"border: 0px;\n"
"image: url(:/newPrefix/Rectangle 5.svg);\n"
"}")
        self.Button_analysis.setObjectName("Button_analysis")
        self.label_text_2 = QtWidgets.QLabel(self.widget)
        self.label_text_2.setGeometry(QtCore.QRect(350, 110, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_text_2.setFont(font)
        self.label_text_2.setStyleSheet("color: rgb(49, 115, 237);")
        self.label_text_2.setObjectName("label_text_2")
        self.Button_exit = QtWidgets.QPushButton(self.widget)
        self.Button_exit.setGeometry(QtCore.QRect(600, 10, 21, 21))
        self.Button_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_exit.setMouseTracking(True)
        self.Button_exit.setStyleSheet("QPushButton\n"
"{\n"
"background-image: url(:/newPrefix/X icone.svg);\n"
"border-image: url(:/newPrefix/X icone.svg);\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    border-image: url(:/newPrefix/X icone_hover.svg);\n"
"\n"
"}\n"
"")
        self.Button_exit.setText("")
        self.Button_exit.setObjectName("Button_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_text_3.setPlainText(_translate("MainWindow", "    Welcome to Our Applcaiton "))
        self.Button_analysis.setText(_translate("MainWindow", "Analyis "))
        self.label_text_2.setText(_translate("MainWindow", "Type Your Comment Here"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
